VideoResolution264=%%StringOfVideoResolution264();%%
FrameRate264=%%StringOfFrameRate264();%%
BitRate264=%%StringOfBitRate264();%%
VideoResolution=%%StringOfVideoResolution();%%
CompressionRate=%%StringOfCompressionRate();%%
FrameRate=%%StringOfFrameRate();%%
ViewMode=%%ViewMode();%%
FrameSize=%%FrameSize();%% Bytes
LightFrequency=%%StringOfLightFrequency();%%
